language: java

jdk: openjdk8

env:
  - NODE_VERSION="12.16.1"

before_install:
  - nvm install $NODE_VERSION
  - node --version

before_script:
  - npm install -g gatsby
  - git clone https://git-r3lab.uni.lu/covid/models.git covid_models

script: 
  - sh java/cd2sbgnml.sh

deploy:
  provider: script
  script:
    - yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: master

