language: java

jdk: openjdk8
node_js: 12

before_script:
  - npm install -g gatsby
  - git clone https://git-r3lab.uni.lu/covid/models.git covid_models

script: 
  - sh java/cd2sbgnml.sh

deploy:
  provider: script
  script:
    - cd npm install && npm run deploy
  skip_cleanup: true
  on:
    branch: master

